### ISSUE TITLE
ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by dep** [starmorph/langchain-js-quickstart#3]
After following the README, `npm run dev` fails with an error:

```
ReferenceError: Headers is not defined
    at createRequest (file:///Users/dpeck/Sites/langchain-js-quickstart/node_modules/langchain/src/util/axios-fetch-adapter.js:273:19)
    at fetchAdapter (file:///Users/dpeck/Sites/langchain-js-quickstart/node_modules/langchain/src/util/axios-fetch-adapter.js:196:19)
    at dispatchRequest (/Users/dpeck/Sites/langchain-js-quickstart/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/Users/dpeck/Sites/langchain-js-quickstart/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/Users/dpeck/Sites/langchain-js-quickstart/node_modules/axios/lib/helpers/bind.js:9:15)
    at /Users/dpeck/Sites/langchain-js-quickstart/node_modules/openai/dist/common.js:149:22
    at /Users/dpeck/Sites/langchain-js-quickstart/node_modules/openai/dist/api.js:1738:133
```

Using Node v16.16.0. Any help is appreciated.

**Comment by dep** [comment]
Update to node `18.15.0` fixed it

**Comment by dep** [comment]
Related https://js.langchain.com/docs/getting-started/install#unsupported-nodejs-16
